### ISSUE TITLE
About axis parameter

### ISSUE THREAD

**Issue by Crispy13** [titu1994/Keras-Group-Normalization#7]
![image](https://user-images.githubusercontent.com/47196430/71950497-c8f10a80-321a-11ea-9f99-938c14322335.png)

Hello titu 1994.

I use group normalization code for my project.

If i use GN after a layer whose output shape is (batch_size, C, D, H, W), is it okay to set axis = 1 because the format is channel-first?

**Comment by titu1994** [comment]
Yes that's fine.
